@urlDev=http://localhost:3000
###Create a new account with phoneNumber
POST {{urlDev}}/user/create-user
content-type: application/json

{
    "phoneNumber":"0936155228",
    "password":"tienismywife"
}

###Verify phoneNumber

POST {{urlDev}}/user/verify-user
content-type: application/json

{
    "phoneNumber":"0936155228",
    "code": 30027
}

###Login with phoneNumber

POST {{urlDev}}/user/login-user
content-type: application/json

{
    "phoneNumber":"09813346154",
    "password":"tienismywife"
}

### Add to cart
POST {{urlDev}}/cart/add-to-cart
Content-Type: application/json

{
    "userId":"63455e6912c233918ec77419",
    "productId":"6341860f3aef1a0dbfbac749",
    "quantity":2,
    "listTopping": [
        {
            "toppingId": "6341b027180933c7ab1ecfe3",
            "quantity": 2,
            "price":20000,
            "name":"abcsdd"
        }
    ]
}

### Remove from cart
DELETE  {{urlDev}}/cart/remove-from-cart
Content-Type: application/json

{
    "userId":"63455e6912c233918ec77419",
    "productId":"6341860f3aef1a0dbfbac749",
    "quantity":2
}

### GET cart
GET {{urlDev}}/cart/get-all-cart?userId=63455e6912c233918ec77419
### Get all product

GET {{urlDev}}/product/get-product
